services:
  db1:
    build: 
      context: ./web1/db
      dockerfile: Dockerfile
    container_name: db1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tiago
      MYSQL_DATABASE: asa1
      MYSQL_USER: tiago
      MYSQL_PASSWORD: tiago
  
  wordpress1:
    depends_on:
      - db1
    build:
      context: ./web1/wp
      dockerfile: Dockerfile
    container_name: wp1
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: tiago
      WORDPRESS_DB_PASSWORD: tiago
      WORDPRESS_DB_NAME: asa1